### ISSUE TITLE
PyScripter can't handle errors in PyQt5 apps

### ISSUE THREAD

**Issue by amr66** [pyscripter/pyscripter#1305]
When running a PyQt5 script which causes an error, PyScripter\Lib\rpyc.zip\rpyc\core\stream.py throwes an error and the error in the script is not detected.

Example:

```
import sys
from qgis.PyQt.QtWidgets import (QApplication,
        QDialog, QTextEdit, QVBoxLayout, QPushButton)

class MyForm(QDialog):

    def __init__(self):
        QDialog.__init__(self)

        self.textEdit = QTextEdit('Hello World!')
        self.buttonOK = QPushButton()
        self.buttonOK.setText('OK')

        self.layout = QVBoxLayout()
        self.layout.addWidget(self.textEdit)

        self.layout.addWidget(self.buttonOK)
        self.setLayout(self.layout)

        self.buttonOK.clicked.connect(self.doOK)

    def doOK(self):
        # error ----------|
        self.textEdit.setTixt("Hello PyQt5!")

app = QApplication(sys.argv)
form = MyForm()
form.show()
app.exec_()
```

Console Output:

```
Traceback (most recent call last):
  File "D:\gisstickX640923\PyScripter\PyScripter\Lib\rpyc.zip\rpyc\core\stream.py", line 214, in read
ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\gisstickX640923\PyScripter\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py", line 208, in __call__
  File "D:\gisstickX640923\PyScripter\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py", line 76, in syncreq
  File "D:\gisstickX640923\PyScripter\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 471, in sync_request
  File "D:\gisstickX640923\PyScripter\PyScripter\Lib\rpyc.zip\rpyc\core\async_.py", line 95, in value
  File "D:\gisstickX640923\PyScripter\PyScripter\Lib\rpyc.zip\rpyc\core\async_.py", line 45, in wait
  File "D:\gisstickX640923\PyScripter\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 387, in serve
  File "D:\gisstickX640923\PyScripter\PyScripter\Lib\rpyc.zip\rpyc\core\channel.py", line 50, in recv
  File "D:\gisstickX640923\PyScripter\PyScripter\Lib\rpyc.zip\rpyc\core\stream.py", line 223, in read
EOFError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
Traceback (most recent call last):
  File "D:\gisstickX640923\PyScripter\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py", line 152, in __getattribute__
  File "D:\gisstickX640923\PyScripter\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py", line 76, in syncreq
  File "D:\gisstickX640923\PyScripter\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 471, in sync_request
  File "D:\gisstickX640923\PyScripter\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 492, in async_request
  File "D:\gisstickX640923\PyScripter\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 477, in _async_request
  File "D:\gisstickX640923\PyScripter\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 259, in _send
  File "D:\gisstickX640923\PyScripter\PyScripter\Lib\rpyc.zip\rpyc\core\channel.py", line 69, in send
  File "D:\gisstickX640923\PyScripter\PyScripter\Lib\rpyc.zip\rpyc\core\stream.py", line 233, in write
  File "D:\gisstickX640923\PyScripter\PyScripter\Lib\rpyc.zip\rpyc\core\stream.py", line 81, in __getattr__
EOFError: stream has been closed
```

**Comment by pyscripter** [comment]
This is due to the fact that PyQt exits on unhandled exception and this breaks the communication between PyScripter and the python that runs PyQt.

You can add an exception handler as follows (uses PyQt6 but should work also with PyQt5):

```python
import sys
from PyQt6.QtWidgets import (QApplication,
        QDialog, QTextEdit, QVBoxLayout, QPushButton)

class MyForm(QDialog):

    def __init__(self):
        QDialog.__init__(self)

        self.textEdit = QTextEdit('Hello World!')
        self.buttonOK = QPushButton()
        self.buttonOK.setText('OK')

        self.layout = QVBoxLayout()
        self.layout.addWidget(self.textEdit)

        self.layout.addWidget(self.buttonOK)
        self.setLayout(self.layout)

        self.buttonOK.clicked.connect(self.doOK)

    def doOK(self):
        # error ----------|
        self.textEdit.setTixt("Hello PyQt5!")

def exception_hook(exctype, value, traceback):
    sys.__excepthook__(exctype, value, traceback)
    #QApplication.quit()  uncomment if you want to quit on exception
sys.excepthook = exception_hook

app = QApplication(sys.argv)
form = MyForm()
form.show()
app.exec()
```

Now you get the error printed without issues.

See also:
- https://stackoverflow.com/questions/55819330/catching-exceptions-raised-in-qapplication
- https://stackoverflow.com/questions/18740884/preventing-pyqt-to-silence-exceptions-occurring-in-slots:

**Comment by amr66** [comment]
Ah! Cool, thank you!

**Comment by amr66** [comment]
Only problem I have now: executed with the exception_hook in the dos console, the `form` is closed, in PyScripter it is not. But I can add a last line to call `form.close()` to make it work.
