### ISSUE TITLE
Multiprocessing not working

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#722]
```
I can't get multiprocessing to work in PyScripter.  I have described two 
examples below.

Example 1 - multiprocessing.Process

What steps will reproduce the problem?
1. Try to run the code example below from a script (obtained from a tutorial at 
http://www.doughellmann.com/PyMOTW/multiprocessing/basics.html).

import multiprocessing

def worker():
    """worker function"""
    print 'Worker'
    return

if __name__ == '__main__':
    jobs = []
    for i in range(5):
        p = multiprocessing.Process(target=worker)
        jobs.append(p)
        p.start()


What is the expected output? What do you see instead?
The expected output is:
Worker
Worker
Worker
Worker
Worker
However, when I run the script, I get no output at all.  It doesn't crash.  It 
just does nothing.

What version of the product are you using? On what operating system?
PyScripter version 2.5.3.0 x86 with python 32-bit 2.7.2 on Windows 7 64-bit

Please provide any additional information below.
If I try to run this same script from IDLE, it does the same thing, producing 
no output but not crashing.  If I run it from a DOS command line, it DOES work.

---------------------------

Example 2 - multiprocessing.Pool

What steps will reproduce the problem?
1. Try to run the code example below from a script (obtained from the python 
doc at http://docs.python.org/2/library/multiprocessing.html).

from multiprocessing import Pool

def f(x):
    return x*x

if __name__ == '__main__':
    pool = Pool(processes=4)              # start 4 worker processes
    result = pool.apply_async(f, [10])    # evaluate "f(10)" asynchronously
    print result.get(timeout=1)           # prints "100" unless your computer is *very* slow
    print pool.map(f, range(10))          # prints "[0, 1, 4,..., 81]"

What is the expected output? What do you see instead?
The expected output is:
100
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

However, when I run the script from PyScripter, I get a TimeoutError from 
pool.py:
Traceback (most recent call last):
  File "<string>", line 254, in run_nodebug
  File "<module3>", line 9, in <module>
  File "C:\Python27\ArcGIS10.1\Lib\multiprocessing\pool.py", line 518, in get
    raise TimeoutError
multiprocessing.TimeoutError

What version of the product are you using? On what operating system?
PyScripter version 2.5.3.0 x86 with python 32-bit 2.7.2 on Windows 7 64-bit

Please provide any additional information below.
If I try to run this same script from IDLE, it works correctly.  If I run it 
from a DOS command line, it also works correctly.

```

Original issue reported on code.google.com by `melindam...@gmail.com` on 28 Jan 2013 at 6:42

**Comment by pyscripter** [comment]
Multiprocessing scripts run from PyScripter are working but multiprocessing creates external processes the output of which is not captured by PyScripter.  You could relay/redirect the output of subprocesses to the main process for printing and you can always use Run, External Run to see the output.

**Comment by pyscripter** [comment]
Console output including multiprocessing output is now redirected to the PyScripter Interpreter window.

**Comment by pyscripter** [comment]
Fixed in version control.

**Comment by vantainguyen** [comment]
> ```
> Just figured out the problem with this on Win 7 anaconda pyscripter 2.6.0
> Pyscripter generates a .pyc file which is what is rerun everytime u run the 
> program, just deleted it and it worked fine for me
> 
> hth
> 
> RK
> ```
> 
> Original comment by `brkris...@gmail.com` on 13 Jul 2015 at 4:30

Hi guy!
Thanks for your info. Could you please show me how to delete the .pyc ?

**Comment by pyscripter** [comment]
@vantainguyen  You are quoting a comment that is 5 years old.   If you using a recent version of PyScripter, multiprocessing should work fine.
