### ISSUE TITLE
ImportError: No module named Tkinter

### ISSUE THREAD

**Issue by GoogleCodeExporter** [pyscripter/pyscripter#794]
```
Hi guys,

I want to show a window using Tkinter, the code just looks like:

try:
    # Python2
    import Tkinter as tk
except ImportError:
    # Python3
    import tkinter as tk
def main():
    win=graphics.GraphWin()
    print win.getWidth()


but Pyscripter give me the error information:

Traceback (most recent call last):
  File "<string>", line 254, in run_nodebug
  File "D:\GoCloud\code\topic\drawpoints.py", line 17, in <module>
    import tkinter as tk
ImportError: No module named tkinter

but in the command environment, there is no error. What's wrong with 
Pyscripter? my Pyscripter version is 2.6 x64


```

Original issue reported on code.google.com by `cameran....@gmail.com` on 29 Apr 2015 at 7:44

**Comment by pyscripter** [comment]
I cannot reproduce this.  By the way the print statement will cause a syntax error in python 3 and the snippet you provide would fail anyway since graphics is not defined.
