### ISSUE TITLE
Cannot import "tqdm" inside pyscripter. DebugOutput instance has no attribute 'closed'

### ISSUE THREAD

**Issue by danieldmm** [pyscripter/pyscripter#812]
Trying to import tqdm (a very easy to use progressbar)...
pip install tqdm
from tqdm import tqdm

Result:

Traceback (most recent call last):
  File "<string>", line 254, in run_nodebug
  File "C:\Users\dd\Documents\Dropbox\PhD\minerva\evaluation\base_index.py", line 12, in <module>
    from tqdm import tqdm
  File "C:\Python27\lib\site-packages\tqdm__init__.py", line 1, in <module>
    from ._tqdm import tqdm
  File "C:\Python27\lib\site-packages\tqdm_tqdm.py", line 14, in <module>
    from ._utils import _supports_unicode, _environ_cols_wrapper, _range, _unich, \
  File "C:\Python27\lib\site-packages\tqdm_utils.py", line 21, in <module>
    colorama.init()
  File "build\bdist.win32\egg\colorama\initialise.py", line 31, in init
  File "build\bdist.win32\egg\colorama\initialise.py", line 61, in wrap_stream
  File "build\bdist.win32\egg\colorama\ansitowin32.py", line 65, in __init__
AttributeError: DebugOutput instance has no attribute 'closed'

**Comment by pyscripter** [comment]
This unit messes up with PyScripter's python input/output redirection.  It tries to close sys.stdout and install its own.  It is suitable for console interpreters and not GUI-based ones such as PyScripter's interpreter.  I am afraid you cannot use it with PyScripter.

**Comment by pyscripter** [comment]
Actually it appears to be working now.  However, you don't get the in-place update of the progress bar.


```
from tqdm import tqdm

def main():
    for i in tqdm(range(1000000)):
        pass

if __name__ == '__main__':
    main()
```

Output


```
 0%|          | 0/1000000 [00:00<?, ?it/s]
 43%|####3     | 432569/1000000 [00:00<00:00, 4291225.59it/s]
 56%|#####6    | 561306/1000000 [00:00<00:00, 2504047.57it/s]
 68%|######8   | 682731/1000000 [00:00<00:00, 1959313.24it/s]
 80%|#######9  | 797036/1000000 [00:00<00:00, 1747034.30it/s]
 91%|######### | 908869/1000000 [00:00<00:00, 1500589.23it/s]
100%|##########| 1000000/1000000 [00:00<00:00, 1416134.39it/s]
```

**Comment by pyscripter** [comment]
tqdm now works as expected.
