### ISSUE TITLE
Large autocomplete possibilities crashes interpreter

### ISSUE THREAD

**Issue by kmclaughlinphd** [pyscripter/pyscripter#873]
I'm working with proprietary modules that are quite large, and noticed that when I mess with the autocomplete in the interpreter, I'll often get stuck in an "EOFError: stream has been closed" loop, forcing me to reinit the python interpreter.

> Traceback (most recent call last):
>  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py", line 196, in __call__
>  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\netref.py", line 71, in syncreq
>  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 429, in sync_request
>  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 229, in _send_request
>  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\protocol.py", line 224, in _send
>  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\channel.py", line 69, in send
>  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\stream.py", line 176, in write
>  File "C:\Program Files (x86)\PyScripter\Lib\rpyc.zip\rpyc\core\stream.py", line 60, in __getattr__
>EOFError: stream has been closed

I found I was able to reproduce the issue quite easily with this code

`def main():
    pass

class foo():
  pass

def add_method(cls, i):
  def somemethod(self):
    print "this is method %d" % i
  somemethod.__doc__ = "generic method"
  somemethod.__name__= "somemethod%d" % i
  setattr(cls, somemethod.__name__,somemethod)

if __name__ == '__main__':
  foobar = foo()
  for i in range(0,10000):
    add_method(foobar, i)
`

Run the code, then drop into the interpreter and type "foobar." then maybe scroll around a little, then type escape (or choose an option, doesn't really matter.

This doesn't seem to happen in e.g., Jupyter, so I assume it's specific to Pyscripter.

**Comment by pyscripter** [comment]
Which version of Pyscripter are you using?  Here on 3.3.3 it copes quite gracefully with the above.  Autocompletion pops up immediately.

**Comment by kmclaughlinphd** [comment]
3.3.2. Remote is 2.7.10 | Anaconda 2.4.0 (32-bit).

This has been a problem for me on two different computers for quite some time, but only recently realized how to reproduce it.

The autocompletion pops up for me, but then crashes the interpreter if i up/down arrow around a bit, then try to do something.

**Comment by pyscripter** [comment]
It coped well with 
```
if __name__ == '__main__':
  foobar = foo()
  for i in range(0,20000:
    add_method(foobar, i)
```
I then tried with 100000 and it did produce the EOF error you mention, although I was able to recover by reinitializing the remote python engine.

**Comment by kmclaughlinphd** [comment]
OK, yes. I am able to recover by reinitializing. Unfortunately, when it occurs during debugging, it's not so convenient.

**Comment by pyscripter** [comment]
I will look into it.

**Comment by pyscripter** [comment]
Are you by any chance using pandas?  If yes have a look at https://groups.google.com/forum/#!topic/pyscripter/GFEmGHe-OEM
